Add scan-interval-ms parameter
intrepidcs/icsscand pull request #13
Opened 2023-07-24 20:33 UTC by j-rge

Allow user to specify the scan interval for searching for devices. Scanning places every interface on the machine in promiscuous mode and currently runs once a second.  This behaviour may have undesirable side-effects and also pollutes the kernel log.

The new parameter --scan-interval-ms <interval> will allow the user to specify the rate at which scanning occurs.  If equal to 0, then only a single scan is performed.

Fixes [#12]

2023-09-08 14:40 UTC, kschwarz-intrepidcs requested changes
Thanks for the  PR!

2023-09-08 14:40 UTC, kschwarz-intrepidcs commented on src/main.cpp
> +       std::cerr << "\t-d,     --daemon\t\t\tRun as a daemon in the background\n";
Tabs to spaces

2023-09-08 14:40 UTC, kschwarz-intrepidcs commented on src/main.cpp
> +               if (scanIntervalMs == 0) {
Please use `if(` and tabs.

2023-09-17 22:17 UTC, j-rge commented on src/main.cpp
> +                       scanIntervalMs = std::atoi(argv[i + 1]);
👍 

```
$ ./libicsneo-socketcan-daemon --scan-interval-ms -10
Invalid input for scan-interval-ms
$ ./libicsneo-socketcan-daemon --scan-interval-ms abcd
Invalid input for scan-interval-ms
$ ./libicsneo-socketcan-daemon --scan-interval-ms 99999999999999999999
Out of range input for scan-interval-ms
```

2023-09-17 22:17 UTC, j-rge commented on src/main.cpp
> +               } else if(arg == "--scan-interval-ms" && i + 1 <= argc) {
👍

2023-09-17 22:17 UTC, j-rge commented on src/main.cpp
> +               if (scanIntervalMs == 0) {
👍

2023-09-17 22:17 UTC, j-rge commented on src/main.cpp
> +       std::cerr << "\t-d,     --daemon\t\t\tRun as a daemon in the background\n";
👍

2023-09-17 22:24 UTC, j-rge commented
@kschwarz-intrepidcs Thanks for the review.

I've been using this addition successfully with `--scan-interval-ms 0` for weeks now with a single NeoVI Fire 3.  I will test with multiple units concurrently to see if it will pick them all up in a single scan.

2023-09-18 14:28 UTC, j-rge commented
@kschwarz-intrepidcs Update: I was able to test with two NeoVI Fire 3 units in the "single scan" mode `--scan-interval-ms 0` and confirm that both units were detected in the scan.

```
$ sudo ./libicsneo-socketcan-daemon --scan-interval-ms 0 &

. . .

$ ip a | grep can
85: can0: <NOARP,ECHO> mtu 72 qdisc noop state DOWN group default qlen 10
    link/can 
    
. . .

119: can31: <NOARP,ECHO> mtu 72 qdisc noop state DOWN group default qlen 10
    link/can
```

2023-09-28 00:35 UTC, merged

2023-09-28 00:35 UTC, kschwarz-intrepidcs commented
Thanks @j-rge!